# Gender Classification Of Names II

youtube : [link](https://www.youtube.com/watch?v=ETVtJe_tvLo&ab_channel=JCharisTech%26J-Secur1ty)

## Importing EDA packages

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [3]:
url = "https://raw.githubusercontent.com/Jcharis/Python-Machine-Learning/master/Gender%20Classification%20With%20%20Machine%20Learning/names_dataset.csv"

df = pd.read_csv(url)

In [5]:
df.head()

index       name sex
0      0       Mary   F
1      1       Anna   F
2      2       Emma   F
3      3  Elizabeth   F
4      4     Minnie   F

In [6]:
df.size

285075

In [12]:
df.columns

Index(['index', 'name', 'sex'], dtype='object')

## Data Types

In [8]:
df.dtypes

index     int64
name     object
sex      object
dtype: object

to make work the data need to become int64

## Check Missing Values

In [9]:
df.isna().sum()

index    0
name     0
sex      0
dtype: int64

### Number of Female

In [10]:
df[df.sex == 'F'].size

181800

### Number of Male

In [11]:
df[df.sex == 'M'].size

103275

## Turn F/M into 0/1

In [13]:
df_names = df

In [14]:
df_names.sex.replace({"F" : 0, "M" : 1}, inplace=True)

In [15]:
df_names.sex.unique()

array([0, 1], dtype=int64)

In [16]:
df_names.dtypes

index     int64
name     object
sex       int64
dtype: object

In [17]:
xfeatures = df_names['name']

## Feature Extraction

In [18]:
cv = CountVectorizer()
x = cv.fit_transform(xfeatures)

In [29]:
cv.get_feature_names()

['aaban',
 'aabha',
 'aabid',
 'aabriella',
 'aada',
 'aadam',
 'aadan',
 'aadarsh',
 'aaden',
 'aadesh',
 'aadhav',
 'aadhavan',
 'aadhi',
 'aadhira',
 'aadhvik',
 'aadhya',
 'aadhyan',
 'aadi',
 'aadian',
 'aadil',
 'aadin',
 'aadish',
 'aadison',
 'aadit',
 'aadith',
 'aadithya',
 'aaditri',
 'aaditya',
 'aadiv',
 'aadon',
 'aadrian',
 'aadrika',
 'aadrit',
 'aadvik',
 'aadvika',
 'aadya',
 'aadyn',
 'aafia',
 'aafreen',
 'aagam',
 'aage',
 'aagot',
 'aahaan',
 'aahan',
 'aahana',
 'aahil',
 'aahir',
 'aahliyah',
 'aahna',
 'aahron',
 'aaidan',
 'aaiden',
 'aaidyn',
 'aaila',
 'aailiyah',
 'aailyah',
 'aaima',
 'aaira',
 'aairah',
 'aaisha',
 'aaishah',
 'aaiyana',
 'aaiza',
 'aaja',
 'aajah',
 'aajaylah',
 'aajon',
 'aakanksha',
 'aakarsh',
 'aakash',
 'aakeem',
 'aakilah',
 'aakira',
 'aakiyah',
 'aakriti',
 'aala',
 'aalaiya',
 'aalaiyah',
 'aalana',
 'aalanah',
 'aalani',
 'aalap',
 'aalaya',
 'aalayah',
 'aalayiah',
 'aalayjah',
 'aalayna',
 'aalaysha',
 'aalaysia',
 'aalea',
 

## Split train and test

In [20]:
from sklearn.model_selection import train_test_split

In [22]:
# Features
x
# Labels
y = df_names.sex

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

## Naive Bayes Classifier

In [49]:
from sklearn.naive_bayes import MultinomialNB

In [50]:
nbc = MultinomialNB()
nbc.fit(x_train, y_train)
nbc.score(x_test, y_test)

0.6406622702399326

In [51]:
# Accuracy of model
print(f"Accuracy is: {round(nbc.score(x_test, y_test)*100, 2)}%")

Accuracy is: 64.07%


## Sample Prediction

In [52]:
# Sampel Prediction
test_name = ['Benny']
vect_name = cv.transform(test_name).toarray()

In [53]:
vect_name

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [54]:
# Predicting female 0, Male 1
nbc.predict(vect_name)

array([1], dtype=int64)

In [58]:
# Sampel2 
test_name1 = ['Luke']
vect_name1 = cv.transform(test_name1)

In [59]:
nbc.predict(vect_name1)

array([1], dtype=int64)

In [60]:
# Sampel3
test_name2 = ['Romanov']
vect_name2 = cv.transform(test_name2)
nbc.predict(vect_name2)

array([0], dtype=int64)

## Sampel in random names

In [61]:
test_name3 = ['Robb', 'Sansa', 'Arya', 'Bran', 'Rickon', 'Snow', 'Daenerys']
vect_name3 = cv.transform(test_name3).toarray()

In [63]:
nbc.predict(vect_name3)

array([1, 0, 1, 1, 0, 0, 0], dtype=int64)

Well we got about 60% gender of names is true, based GoT (4/7)

## Make Function

In [74]:
def sex_predict(name):
    test_name = [name]
    vect_name = cv.transform(test_name).toarray()
    if nbc.predict(vect_name) == 0:
        return 'Female'
    else:
        return 'Male'

In [75]:
sex_predict('Nazz')

'Female'

In [76]:

# Test in list
namelist = ['Doeksoen', 'Jungpal', 'Choi', 'Bora', 'Sunwoo']
for name in namelist:
    print(f"{name} is", sex_predict(name))

Doeksoen is Female
Jungpal is Female
Choi is Female
Bora is Male
Sunwoo is Female


Well the prediction is bad for Reply 1988 characters

## Using custom function for feature analysis 

In [77]:
def features(name):
    name = name.lower()
    return {
        'first-letter': name[0],
        'first2-letters': name[0:2],
        'first3-letters': name[0:3],
        'last-letter': name[-1],
        'last2-letters': name[-2:],
        'last3-letters': name[-3:],
    }

In [78]:
## Vectorize feature function
features = np.vectorize(features)
print(features(['Doeksoen', 'Jungpal', 'Choi', 'Bora', 'Sunwoo']))

[{'first-letter': 'd', 'first2-letters': 'do', 'first3-letters': 'doe', 'last-letter': 'n', 'last2-letters': 'en', 'last3-letters': 'oen'}
 {'first-letter': 'j', 'first2-letters': 'ju', 'first3-letters': 'jun', 'last-letter': 'l', 'last2-letters': 'al', 'last3-letters': 'pal'}
 {'first-letter': 'c', 'first2-letters': 'ch', 'first3-letters': 'cho', 'last-letter': 'i', 'last2-letters': 'oi', 'last3-letters': 'hoi'}
 {'first-letter': 'b', 'first2-letters': 'bo', 'first3-letters': 'bor', 'last-letter': 'a', 'last2-letters': 'ra', 'last3-letters': 'ora'}
 {'first-letter': 's', 'first2-letters': 'su', 'first3-letters': 'sun', 'last-letter': 'o', 'last2-letters': 'oo', 'last3-letters': 'woo'}]


In [79]:
# Etract the features for the dataset
df_x = features(df_names['name'])

In [80]:
df_y = df_names['sex']

## DictVcorizer

In [81]:
from sklearn.feature_extraction import DictVectorizer

corpus = features(['Bruno', 'Marry'])
dv = DictVectorizer()
dv.fit(corpus)
transformed = dv.transform(corpus)
print(transformed)

  (0, 0)	1.0
  (0, 2)	1.0
  (0, 4)	1.0
  (0, 6)	1.0
  (0, 8)	1.0
  (0, 11)	1.0
  (1, 1)	1.0
  (1, 3)	1.0
  (1, 5)	1.0
  (1, 7)	1.0
  (1, 9)	1.0
  (1, 10)	1.0


In [82]:
dv.get_feature_names()

['first-letter=b',
 'first-letter=m',
 'first2-letters=br',
 'first2-letters=ma',
 'first3-letters=bru',
 'first3-letters=mar',
 'last-letter=o',
 'last-letter=y',
 'last2-letters=no',
 'last2-letters=ry',
 'last3-letters=rry',
 'last3-letters=uno']

In [83]:
dfx_train, dfx_test, dfy_train, dfy_test = train_test_split(df_x, df_y, test_size=0.3, random_state=42)

In [84]:
dfx_train

array([{'first-letter': 'n', 'first2-letters': 'ni', 'first3-letters': 'nic', 'last-letter': 'a', 'last2-letters': 'ra', 'last3-letters': 'ora'},
       {'first-letter': 't', 'first2-letters': 'te', 'first3-letters': 'tek', 'last-letter': 'a', 'last2-letters': 'ma', 'last3-letters': 'ema'},
       {'first-letter': 'o', 'first2-letters': 'ob', 'first3-letters': 'obe', 'last-letter': 'a', 'last2-letters': 'ra', 'last3-letters': 'era'},
       ...,
       {'first-letter': 'j', 'first2-letters': 'ja', 'first3-letters': 'jaz', 'last-letter': 'y', 'last2-letters': 'ly', 'last3-letters': 'zly'},
       {'first-letter': 'e', 'first2-letters': 'el', 'first3-letters': 'elv', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'ina'},
       {'first-letter': 'l', 'first2-letters': 'le', 'first3-letters': 'led', 'last-letter': 'r', 'last2-letters': 'er', 'last3-letters': 'ger'}],
      dtype=object)

In [85]:
dv = DictVectorizer()
dv.fit_transform(dfx_train)

<66517x8287 sparse matrix of type '<class 'numpy.float64'>'
	with 399102 stored elements in Compressed Sparse Row format>

## Model Building Using Decision Tree

In [86]:
from sklearn.tree import DecisionTreeClassifier

dtree = DecisionTreeClassifier()
my_xfeature = dv.transform(dfx_train)
dtree.fit(my_xfeature, dfy_train)

DecisionTreeClassifier()

In [87]:
test_name_example = ['Benjamin']
transform_dv = dv.transform(features(test_name_example))

In [88]:
vect_name_example = transform_dv.toarray()

In [89]:
# Predict gender of names
dtree.predict(vect_name_example)

array([1], dtype=int64)

In [90]:
if dtree.predict(vect_name_example) == 0:
    print('Female')
else:
    print('Male')

Male


In [94]:
def sex_predict1(name):
    test_name1 = [name]
    transform_dv = dv.transform(features(test_name1))
    vect_name = transform_dv.toarray()
    if dtree.predict(vect_name) == 0:
        return 'Female'
    else:
        return 'Male'

In [95]:
randomlist = ['Alex', 'Ferguso', 'Snow', 'Peter', 'Susan', 'Claire']

In [96]:
for name in randomlist:
    print(f"{name} is {sex_predict1(name)}")

Alex is Male
Ferguso is Male
Snow is Male
Peter is Male
Susan is Female
Claire is Male


It seems we false only in last ones

In [97]:
got_list = ['Robb', 'Sansa', 'Arya', 'Bran', 'Rickon', 'Snow', 'Daenerys']

for name in got_list:
    print(f"{name} is {sex_predict1(name)}")

Robb is Male
Sansa is Female
Arya is Male
Bran is Male
Rickon is Male
Snow is Male
Daenerys is Female


Only one is wrong, but is fine, because Arya actually is male name in my country

In [98]:
reply_list = ['Doeksoen', 'Jungpal', 'Choi', 'Bora', 'Sunwoo']

for name in reply_list:
    print(f"{name} is {sex_predict1(name)}")

Doeksoen is Male
Jungpal is Male
Choi is Male
Bora is Male
Sunwoo is Male


I think Asian names is hard to predict :( - well 3/5 is right

In [99]:
# Predicting score for data train
dtree.score(dv.transform(dfx_train), dfy_train)

0.9884390456575011

In [100]:
# Predicting score for data test
dtree.score(dv.transform(dfx_test), dfy_test)

0.8660025256068472

## Saving our model

### Using joblib

In [102]:
import joblib

In [103]:
decision_tree_model = open('decisiontreemodel.pkl', 'wb')

In [104]:
joblib.dump(dtree, decision_tree_model)

In [105]:
decision_tree_model.close()

### Using Pickle 

In [106]:
import pickle

In [107]:
dtree_model = open('decisiontrreemodel_using_pickle.pkl', 'wb')

In [108]:
pickle.dump(dtree, dtree_model)

In [109]:
dtree_model.close()

### Save NaiveBayesian

In [110]:
naive_bayes_model = open('naivebayesmodel.pkl', 'wb')
joblib.dump(nbc, naive_bayes_model)
naive_bayes_model.close()