## Training

Actually you can skip into the step 3, because it same with the step 3

The purpose is to build the model which we run in step 4

If you don't see the model, perhaps my configuration of *.gitignore* is success

In [1]:
import pickle

In [2]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [3]:
X

array([[[ 32,  35,  55, ...,  79,  86, 153],
        [ 32,  36,  55, ...,  26,  54,  67],
        [ 30,  35,  55, ...,   6,  17,  16],
        ...,
        [143, 146, 145, ..., 125, 118, 107],
        [144, 144, 144, ..., 128, 126, 115],
        [142, 140, 144, ..., 126, 126, 114]],

       [[ 81,  81,  81, ...,  30,  29,  30],
        [ 86,  88,  84, ...,  31,  31,  31],
        [ 91,  91,  91, ...,  34,  32,  32],
        ...,
        [ 16,  16,  16, ...,  17,  13,   8],
        [ 13,  13,  13, ..., 178, 124,  97],
        [ 12,  12,  12, ..., 226, 170, 125]],

       [[ 48,  48,  25, ...,   6,  55,  16],
        [  6,  21,  45, ...,  26,  77,  36],
        [ 28,  63,   8, ...,  38,  34,   9],
        ...,
        [ 31,  23,  29, ...,  91,  86,  81],
        [ 24,  13,  26, ...,  86,  76,  68],
        [ 22,  18,  20, ...,  77,  73,  63]],

       ...,

       [[  6,  20,  24, ...,  77,  90,  90],
        [ 15,   7,  19, ..., 103,  60,  77],
        [ 16,  19,  20, ...,  61,  92,  96

In [4]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [5]:
X = X/255

In [6]:
X

array([[[0.1254902 , 0.1372549 , 0.21568627, ..., 0.30980392,
         0.3372549 , 0.6       ],
        [0.1254902 , 0.14117647, 0.21568627, ..., 0.10196078,
         0.21176471, 0.2627451 ],
        [0.11764706, 0.1372549 , 0.21568627, ..., 0.02352941,
         0.06666667, 0.0627451 ],
        ...,
        [0.56078431, 0.57254902, 0.56862745, ..., 0.49019608,
         0.4627451 , 0.41960784],
        [0.56470588, 0.56470588, 0.56470588, ..., 0.50196078,
         0.49411765, 0.45098039],
        [0.55686275, 0.54901961, 0.56470588, ..., 0.49411765,
         0.49411765, 0.44705882]],

       [[0.31764706, 0.31764706, 0.31764706, ..., 0.11764706,
         0.11372549, 0.11764706],
        [0.3372549 , 0.34509804, 0.32941176, ..., 0.12156863,
         0.12156863, 0.12156863],
        [0.35686275, 0.35686275, 0.35686275, ..., 0.13333333,
         0.1254902 , 0.1254902 ],
        ...,
        [0.0627451 , 0.0627451 , 0.0627451 , ..., 0.06666667,
         0.05098039, 0.03137255],
        [0.0

In [7]:
X.shape

(25000, 60, 60)

In [8]:
y.shape

(25000,)

In [10]:
X = X.reshape(-1, 60, 60, 1)

In [12]:
X.shape

(25000, 60, 60, 1)

In [13]:
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten
from keras.models import Sequential

In [14]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape=X.shape[1:],activation='relu'))

model.add(Dense(2, activation='softmax'))

In [15]:
model.compile(optimizer='adam',
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])

In [16]:
model.fit(X, y, epochs=5, validation_split=0.1)

Epoch 1/5
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmpqrw8lh_6.py, line 48)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmpqrw8lh_6.py, line 48)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
704/704 [==============================] - 96s 109ms/step - loss: 0.6584 - accuracy: 0.5966 - val_loss: 0.5411 - val_accuracy: 0.7268
Epoch 2/5
704/704 [==============================] - 77s 109ms/step - loss: 0.5062 - accuracy: 0.7554 - val_loss: 0.5139 - val_accuracy: 0.7528
Epoch 3/5
704/704 [==============================] - 84s 119ms/step - loss: 0.4504 - accuracy: 0.7893 - val_

In [17]:
X.shape

(25000, 60, 60, 1)